[package]
name = "synacor_cpu"
version = "0.1.0"
authors = ["user <you@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
sdl2 = "0.34"
serde = { version = "1.0", features=["derive"] }
serde_json = "1.0"